### ISSUE TITLE
/usr/share/plymouth/themes/os1/os1.plymouth does not exist

### ISSUE THREAD

**Issue by Guaxinim5573** [t-gitt/OS1#2]
While installing this theme and using the command `plymouth-set-default-theme os1 -R`, an error occurs.

```
$ sudo plymouth-set-default-theme os1 -R
/usr/share/plymouth/themes/os1/os1.plymouth does not exist
```

Using Arch Linux.

**Comment by t-gitt** [comment]
thanks for the contribution. I have merged your commits to main branch
